import 'package:psalmody/models/psalm.dart';

const PSALMS_DATA = const [
//  Psalm(
//    id: ,
//    title: 'Salmo ',
//    lyrics: [
//
//    ],
//  ),
  Psalm(
    id: 1,
    title: 'Salmo 1b',
    lyrics: [
      '1 Quão bem aventurado é',
      'o homem que não anda',
      'conforme as ímpias sugestões',
      'de conselheiros maus',
      '',
      'Não se detém no caminhar',
      'de homens pecadores',
      'Nem se assenta em comunhão',
      'com o escarnecedor.',
      '',
      '2 Porém o seu prazer está',
      'na santa lei de Deus',
      'E dia e noite nessa lei',
      'medita sem cessar.',
      '',
      '3 Qual árvore plantada está',
      'junto das muitas águas',
      'tal é o homem, pois no tempo',
      'o fruto próprio dá',
      '',
      'E murcha não será jamais',
      'toda sua folhagem',
      'Bem sucedido ele será',
      'em tudo que fizer',
      '',
      '4 Os ímpios nunca são assim,',
      'são como a palha ao vento',
      '5 no juízo e na congregação',
      'dos justos,  cairão',
      '',
      '6 Pois o Senhor conhece bem',
      'dos justos a vereda',
      'mas o caminho dos perversos,',
      'sim, perecerá.',
    ],
  ),
  Psalm(
    id: 2,
    title: 'Salmo 2',
    lyrics: [
      'Por que se amotinam as nações,',
      'pensam os povos sempre em vaidades?',
      'Os reis da terra tomam posições',
      'e_os governantes buscam unidade',
      'Contra o Senhor e contra Seu Ungido',
      'Dizendo: “Os laços seus vamos romper',
      'Suas algemas lançaremos fora',
      'deles queremos nós nos desfazer.”',
      '',
      'Porém Aquele que nos céus está',
      'Põe-se a rir, o Senhor zomba deles',
      'Na sua ira há de lhes falar',
      'no Seu furor os deixará turbados:',
      'Constitui meu Rei, o meu Ungido',
      'Sobre o meu santo monte de Sião',
      'Proclamarei do Senhor seu decreto:',
      'Disse:  “és Meu Filho, hoje Te gerei”.',
      '',
      'Pede a mim, e herdarás nações',
      'e os fins da terra como Tua posse',
      'com Teu bastão de ferro_as quebrarás',
      'qual vaso de oleiro despedaçarás.',
      'Agora pois ó reis sede prudentes',
      'deixai-vos ó juízes exortar',
      'prestai a Deus serviço com temor',
      'e alegrai-vos nele com tremor.',
      '',
      'Beijai o Filho, Ungido do Senhor',
      'Para que sua ira não se acenda',
      'E no caminho ainda pereçais',
      'Quando em breve Seu furor se levantar',
      'São todos nEle bem aventurados',
      'Todo que nele se refugiar',
      'São todos nEle bem aventurados',
      'Todo que nele se refugiar.',
    ],
  ),
  Psalm(
    id: 3,
    title: 'Salmo 3b',
    lyrics: [
      '1 Senhor, como aumentam contra mim',
      'Os opositores meus',
      '2 São muitos que proferem contra mim:',
      '“Nem Deus o salvará”',
      '',
      '3 Tu és minha glória,_escudo meu.',
      'Exaltas o servo teu.',
      '4 Clamei com minha voz: responde-me',
      'Do santo monte Seu.',
      '',
      '5 E pego no sono ao deitar',
      'Acordo, pois me susténs',
      '6 Não temo_a multidão ao meu redor',
      'Que contra mim está.',
      '',
      '7 Levanta-te ó Deus, vem me salvar',
      'Feriste_inimigos meus',
      'Seus dentes e seus queixos quebrastes,',
      'Ferindo-os de_uma vez.',
      '',
      '8 Ao Senhor Javé, o nosso Deus,',
      'Pertence a salvação',
      'A bênção divinal esteja, pois,',
      'No povo Teu, Senhor.',
    ],
  ),
  Psalm(
    id: 4,
    title: 'Salmo 4b',
    lyrics: [
      '1. Deus, justiça minha, ouve eu clamo a ti,',
      'Tens me aliviado na angústia e dor',
      'Tem misericórdia de mim, quando clamo',
      'Ouve a minha prece; minha oração.',
      '',
      '2. Homens, até quando vós transformareis',
      'Em vexame a minha glória e esplendor?',
      'Homens até quando, amareis vaidades?',
      'Até quando a vil mentira buscareis?',
      '',
      '3. Mas sabei que Deus distingue Seus fiéis,',
      'O Senhor me ouve, quando eu clamar',
      '4. Irai-vos e não pequeis, e no travesseiro',
      'Consultai o coração e sossegai.',
      '',
      '5. Sacrifícios de justiça oferecei',
      'No Senhor esteja vosso confiar',
      '6. Muitos dizem: “Quem a nós,',
      'o bem nos fará saber?”',
      'A luz do Teu rosto, ergue sobre nós.',
      '',
      '7. Pões mais alegria no meu coração',
      'do que quando a eles, sobram vinho e pão',
      '8. e em paz me deito,',
      'sem demora o sono vem',
      'Pois só Deus me faz seguro repousar.',
    ],
  ),
//  Psalm(
//    id: ,
//    title: 'Salmo ',
//    lyrics: [
//
//    ],
//  ),
  Psalm(
    id: 6,
    title: 'Salmo 6b',
    lyrics: [
      '1.Não me reproves, ó Senhor',
      'nem me castigues no furor',
      '2. Tem compaixão de mim, Senhor',
      'porque enfraquecido_estou',
      'Vem me sarar, Senhor, porque',
      'bem fracos_os_ossos meus estão.',
      '',
      '3. Também a minha alma_está',
      'profundamente em terror',
      'Mas Tu, Senhor, quando_agirás?',
      '4. Volta, Senhor, e livra-me!',
      'Por Teu favor vem me salvar',
      '5. Nem tumba e morte dão louvor.',
      '',
      '6.  Estou cansado de gemer',
      'Às noites faço alagar',
      'De lágrimas meu leito encher',
      '7. Meus olhos tristes mágoas têm',
      'amortecidos, fracos são',
      'por tantos inimigos meus.',
      '',
      '8. De mim distantes estejais',
      'Vós todos que fazeis o mal',
      'Pois Deus o meu lamento_ouviu',
      "9. E acolheu minh'oração",
      '10. Envergonhados fugirão',
      'Os inimigos de_uma vez.',
    ],
  ),
//  Psalm(
//    id: ,
//    title: 'Salmo ',
//    lyrics: [
//
//    ],
//  ),
//  Psalm(
//    id: ,
//    title: 'Salmo ',
//    lyrics: [
//
//    ],
//  ),
  Psalm(
    id: 9,
    title: 'Salmo 9b',
    lyrics: [
      '1. Senhor, eu Te louvo, com todo meu ser',
      'E Tuas proezas, todas contarei',
      '2. Em Ti me alegro e exultarei',
      'ao Teu nome_excelso louvor cantarei.',
      '',
      '3. Ao retrocederem inimigos meus',
      'tropeçam e caem diante de Ti',
      '4. Pois firmas minha_causa, o direito meu',
      'No trono te_assentas com justo julgar.',
      '',
      '5. Censuras nações, e o ímpio destróis',
      'Apagas seu nome, por tempos sem fim.',
      '6. Quanto_aos inimigos, consumidos são',
      'Ruínas perpétuas, cidades no chão.',
      '',
      'Nenhuma memória deles perdurou',
      '7. Mas fica no trono pra sempre_o Senhor',
      'No trono erguido com_o fim de julgar',
      '8. o mundo e_os povos com justo padrão.',
      '',
      '9. Refúgio_é_o Senhor ao opresso também',
      'Refúgio nas horas de tribulação',
      '10. Confiam em Ti, quem Teu nome detém',
      'Porque Tu Senhor nunca deixas os Teus.',
      '',
      '11.Cantai os louvores ao Deus de Sião',
      'Dizei entre_os povos, os feitos de Deus',
      '12.  Pois lembra-se Aquele que_o sangue requer',
      'e não se esquece do_aflito_o clamor.',
      '',
      '13.  Tem misericórdia, de mim, ó Senhor',
      'E vê quantas dores me deram os maus',
      'Os que me odeiam me fazem sofrer',
      'Das portas da morte me salvas ó Deus',
      '',
      '14. E assim entrarei com louvor em Sião',
      'Cantando nas portas, Tua salvação',
      '15. Na cova que_abriram, nações cairão',
      'O laço que_armaram, prendeu-lhes o pé.',
      '',
      '16.  E bem conhecido se torna_o Senhor',
      'Por causa dos seus julgamentos que faz',
      'Enlaçado_o_ímpio, envolto está',
      'Nas obras traçadas pela própria mão.',
      '',
      '17. Os ímpios no_inferno lançados serão',
      'Também as nações que se_esquecem de Deus',
      '18. O pobre pra sempre_esquecido não é',
      'Nem se frustrará sempre_o seu esperar.',
      '',
      '19.  Levanta-Te_ó Deus, que não vença_o mortal',
      'E julgues na Tua presença_as nações',
      '20. Infunde-lhes medo Senhor; e_as nações',
      'Cientes serão que são simples mortais',
    ],
  ),
//  Psalm(
//    id: ,
//    title: 'Salmo ',
//    lyrics: [
//
//    ],
//  ),
//  Psalm(
//    id: ,
//    title: 'Salmo ',
//    lyrics: [
//
//    ],
//  ),
//  Psalm(
//    id: ,
//    title: 'Salmo ',
//    lyrics: [
//
//    ],
//  ),
//  Psalm(
//    id: ,
//    title: 'Salmo ',
//    lyrics: [
//
//    ],
//  ),
//  Psalm(
//    id: ,
//    title: 'Salmo ',
//    lyrics: [
//
//    ],
//  ),
  Psalm(
    id: 15,
    title: 'Salmo 15b',
    lyrics: [
      '\u00B9Quem vai morar, Senhor,',
      'no teu santo templo?',
      'Quem há de residir',
      'no teu monte, ó Deus?',
      '\u00B2Quem vive em retidão,',
      'tem justo proceder',
      'Só a verdade diz',
      'no seu coração.',
      '',
      '\u00B3Não vive a difamar,',
      'não faz mal a outrem:',
      'Ao seu vizinho não',
      'quer injuriar',
      '\u2074Despreza o homem vil,',
      'honra ao que teme a Deus;',
      'Jura com perda,',
      'até, mas não volta atrás.',
      '',
      '\u2075O seu dinheiro não',
      'cede com usura,',
      'Suborno algum jamais',
      'pensa receber',
      'Para incriminar',
      'quem inocente é',
      'Quem assim proceder,',
      'não se abalará.',
    ],
  ),
  Psalm(
    id: 23,
    title: 'Salmo 23b',
    lyrics: [
      '\u00B9O meu pastor é o Senhor',
      'E nada me faltará',
      'Em pastos verdes faz-me deitar,',
      'As fontes de paz conduz.',
      '',
      "\u00B2Minha'alma Deus bem restaurar",
      'E guia meu caminhar:',
      'Por justas veredas faz-me andar',
      'Por causa do nome Seu.',
      '',
      '\u00B3Se a morte me ameaçar',
      'No vale da escuridão',
      'Não temerei mal nenhum',
      'Pois tu comigo estás.',
      '',
      '\u2074A tua vara e o teu bordão',
      'A mim consolo dão',
      'E mesa pões diante de mim.',
      'Perante inimigos meus.',
      '',
      '\u2075Com óleo a fronte unges-me',
      'Transborda o copo meu',
      'Bondade tua e compaixão',
      'Deveras me sequirão.',
      '',
      '\u2076Sim, todos os dias me seguirão,',
      'Por todo o meu viver',
      'E eternamente habitarei',
      'Na casa do Senhor.',
    ],
  ),
];
