import 'package:psalmody/models/psalm.dart';

const PSALMS_DATA = const [
  Psalm(
    id: 15,
    title: 'Salmo 15b',
    lyrics: [
      '\u00B9Quem vai morar, Senhor,',
      'no teu santo templo?',
      'Quem há de residir',
      'no teu monte, ó Deus?',
      '\u00B2Quem vive em retidão,',
      'tem justo proceder',
      'Só a verdade diz',
      'no seu coração.',
      '',
      '\u00B3Não vive a difamar,',
      'não faz mal a outrem:',
      'Ao seu vizinho não',
      'quer injuriar',
      '\u2074Despreza o homem vil,',
      'honra ao que teme a Deus;',
      'Jura com perda,',
      'até, mas não volta atrás.',
      '',
      '\u2075O seu dinheiro não',
      'cede com usura,',
      'Suborno algum jamais',
      'pensa receber',
      'Para incriminar',
      'quem inocente é',
      'Quem assim proceder,',
      'não se abalará.',
    ],
  ),
  Psalm(
    id: 23,
    title: 'Salmo 23b',
    lyrics: [
      '\u00B9O meu pastor é o Senhor',
      'E nada me faltará',
      'Em pastos verdes faz-me deitar,',
      'As fontes de paz conduz.',
      '',
      "\u00B2Minha'alma Deus bem restaurar",
      'E guia meu caminhar:',
      'Por justas veredas faz-me andar',
      'Por causa do nome Seu.',
      '',
      '\u00B3Se a morte me ameaçar',
      'No vale da escuridão',
      'Não temerei mal nenhum',
      'Pois tu comigo estás.',
      '',
      '\u2074A tua vara e o teu bordão',
      'A mim consolo dão',
      'E mesa pões diante de mim.',
      'Perante inimigos meus.',
      '',
      '\u2075Com óleo a fronte unges-me',
      'Transborda o copo meu',
      'Bondade tua e compaixão',
      'Deveras me sequirão.',
      '',
      '\u2076Sim, todos os dias me seguirão,',
      'Por todo o meu viver',
      'E eternamente habitarei',
      'Na casa do Senhor.',
    ],
  ),

];
