import 'package:psalmody/models/psalm.dart';

const PSALMS_DATA = const [
  Psalm(
    id: 1,
    title: 'Salmo 1b',
    lyrics: [
      '1 Quão bem aventurado é',
      'o homem que não anda',
      'conforme as ímpias sugestões',
      'de conselheiros maus',
      '',
      'Não se detém no caminhar',
      'de homens pecadores',
      'Nem se assenta em comunhão',
      'com o escarnecedor.',
      '',
      '2 Porém o seu prazer está',
      'na santa lei de Deus',
      'E dia e noite nessa lei',
      'medita sem cessar.',
      '',
      '3 Qual árvore plantada está',
      'junto das muitas águas',
      'tal é o homem, pois no tempo',
      'o fruto próprio dá',
      '',
      'E murcha não será jamais',
      'toda sua folhagem',
      'Bem sucedido ele será',
      'em tudo que fizer',
      '',
      '4 Os ímpios nunca são assim,',
      'são como a palha ao vento',
      '5 no juízo e na congregação',
      'dos justos,  cairão',
      '',
      '6 Pois o Senhor conhece bem',
      'dos justos a vereda',
      'mas o caminho dos perversos,',
      'sim, perecerá.',
    ],
  ),
  Psalm(
    id: 2,
    title: 'Salmo 2',
    lyrics: [
      'Por que se amotinam as nações,',
      'pensam os povos sempre em vaidades?',
      'Os reis da terra tomam posições',
      'e_os governantes buscam unidade',
      'Contra o Senhor e contra Seu Ungido',
      'Dizendo: “Os laços seus vamos romper',
      'Suas algemas lançaremos fora',
      'deles queremos nós nos desfazer.”',
      '',
      'Porém Aquele que nos céus está',
      'Põe-se a rir, o Senhor zomba deles',
      'Na sua ira há de lhes falar',
      'no Seu furor os deixará turbados:',
      'Constitui meu Rei, o meu Ungido',
      'Sobre o meu santo monte de Sião',
      'Proclamarei do Senhor seu decreto:',
      'Disse:  “és Meu Filho, hoje Te gerei”.',
      '',
      'Pede a mim, e herdarás nações',
      'e os fins da terra como Tua posse',
      'com Teu bastão de ferro_as quebrarás',
      'qual vaso de oleiro despedaçarás.',
      'Agora pois ó reis sede prudentes',
      'deixai-vos ó juízes exortar',
      'prestai a Deus serviço com temor',
      'e alegrai-vos nele com tremor.',
      '',
      'Beijai o Filho, Ungido do Senhor',
      'Para que sua ira não se acenda',
      'E no caminho ainda pereçais',
      'Quando em breve Seu furor se levantar',
      'São todos nEle bem aventurados',
      'Todo que nele se refugiar',
      'São todos nEle bem aventurados',
      'Todo que nele se refugiar.',
    ],
  ),
  Psalm(
    id: 3,
    title: 'Salmo 3b',
    lyrics: [
      '1 Senhor, como aumentam contra mim',
      'Os opositores meus',
      '2 São muitos que proferem contra mim:',
      '“Nem Deus o salvará”',
      '',
      '3 Tu és minha glória,_escudo meu.',
      'Exaltas o servo teu.',
      '4 Clamei com minha voz: responde-me',
      'Do santo monte Seu.',
      '',
      '5 E pego no sono ao deitar',
      'Acordo, pois me susténs',
      '6 Não temo_a multidão ao meu redor',
      'Que contra mim está.',
      '',
      '7 Levanta-te ó Deus, vem me salvar',
      'Feriste_inimigos meus',
      'Seus dentes e seus queixos quebrastes,',
      'Ferindo-os de_uma vez.',
      '',
      '8 Ao Senhor Javé, o nosso Deus,',
      'Pertence a salvação',
      'A bênção divinal esteja, pois,',
      'No povo Teu, Senhor.',
    ],
  ),
  Psalm(
    id: 4,
    title: 'Salmo 4b',
    lyrics: [
      '1. Deus, justiça minha, ouve eu clamo a ti,',
      'Tens me aliviado na angústia e dor',
      'Tem misericórdia de mim, quando clamo',
      'Ouve a minha prece; minha oração.',
      '',
      '2. Homens, até quando vós transformareis',
      'Em vexame a minha glória e esplendor?',
      'Homens até quando, amareis vaidades?',
      'Até quando a vil mentira buscareis?',
      '',
      '3. Mas sabei que Deus distingue Seus fiéis,',
      'O Senhor me ouve, quando eu clamar',
      '4. Irai-vos e não pequeis, e no travesseiro',
      'Consultai o coração e sossegai.',
      '',
      '5. Sacrifícios de justiça oferecei',
      'No Senhor esteja vosso confiar',
      '6. Muitos dizem: “Quem a nós,',
      'o bem nos fará saber?”',
      'A luz do Teu rosto, ergue sobre nós.',
      '',
      '7. Pões mais alegria no meu coração',
      'do que quando a eles, sobram vinho e pão',
      '8. e em paz me deito,',
      'sem demora o sono vem',
      'Pois só Deus me faz seguro repousar.',
    ],
  ),
  Psalm(
    id: 5,
    title: 'Salmo 5',
    lyrics: [
      '1. Ouve Senhor pois clamo a Ti',
      'Ao meu gemido acode',
      '2. Ouve meu Rei e Deus, o clamor',
      'Pois Te imploro, ó Senhor.',
      '3. Ouves minha voz de manhã',
      'Cedo exponho a minha oração',
      'E_esperando ficarei',
      'E esperando ficarei.',
      '',
      '4. Pois não és Deus que tenhas prazer,',
      'nas obras da iniquidade.',
      'Contigo o mal não pode_habitar',
      'Contigo o mal não ficará.',
      '5. Arrogantes não poderão',
      'A Tua vista permanecer',
      'Aborreces todo que',
      'a maldade praticar.',
      '',
      '6. Os mentirosos Tu destróis',
      'O cruel, enganador',
      'Os abomina o Senhor',
      'Os abomina o Senhor.',
      '7. Eu porém por Teu rico amor',
      'em Tua casa_assim entrarei',
      'e alí me prostrarei',
      'em Teu temor no templo_estar',
      '',
      '8. Em justiça guia-me',
      'por causa dos que se_opõem',
      'endireita ante mim',
      'o Teu caminho, ó Senhor.',
      '9. Lábios desleais eles tem',
      'Criminosos no seu pensar',
      'Cova aberta ao falar',
      'E com a boca_a adular.',
      '',
      '10. E condena-os já ó Deus',
      'Caiam por conselhos seus',
      'por suas muitas transgressões',
      'Rejeita-os pois rebeldes são.',
      '11. Mas os que confiam em Ti',
      'Folguem sempre a jubilar',
      'Pois defesa lhes darás',
      'Pois defesa lhes darás.',
      '',
      'E exultem no Senhor',
      'Quem amar Teu nome ó Deus.',
      '12. Pois a Tua bênção dás',
      'ao que é justo a darás.',
      'Como escudo a defender',
      'o Teu justo cercarás',
      'Da Tua bondade_ó Deus',
      'o Teu justo cercarás.',
    ],
  ),
  Psalm(
    id: 6,
    title: 'Salmo 6b',
    lyrics: [
      '1.Não me reproves, ó Senhor',
      'nem me castigues no furor',
      '2. Tem compaixão de mim, Senhor',
      'porque enfraquecido_estou',
      'Vem me sarar, Senhor, porque',
      'bem fracos_os_ossos meus estão.',
      '',
      '3. Também a minha alma_está',
      'profundamente em terror',
      'Mas Tu, Senhor, quando_agirás?',
      '4. Volta, Senhor, e livra-me!',
      'Por Teu favor vem me salvar',
      '5. Nem tumba e morte dão louvor.',
      '',
      '6.  Estou cansado de gemer',
      'Às noites faço alagar',
      'De lágrimas meu leito encher',
      '7. Meus olhos tristes mágoas têm',
      'amortecidos, fracos são',
      'por tantos inimigos meus.',
      '',
      '8. De mim distantes estejais',
      'Vós todos que fazeis o mal',
      'Pois Deus o meu lamento_ouviu',
      "9. E acolheu minh'oração",
      '10. Envergonhados fugirão',
      'Os inimigos de_uma vez.',
    ],
  ),
  Psalm(
    id: 7,
    title: 'Salmo 7',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 8,
    title: 'Salmo 8',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 9,
    title: 'Salmo 9b',
    lyrics: [
      '1. Senhor, eu Te louvo, com todo meu ser',
      'E Tuas proezas, todas contarei',
      '2. Em Ti me alegro e exultarei',
      'ao Teu nome_excelso louvor cantarei.',
      '',
      '3. Ao retrocederem inimigos meus',
      'tropeçam e caem diante de Ti',
      '4. Pois firmas minha_causa, o direito meu',
      'No trono te_assentas com justo julgar.',
      '',
      '5. Censuras nações, e o ímpio destróis',
      'Apagas seu nome, por tempos sem fim.',
      '6. Quanto_aos inimigos, consumidos são',
      'Ruínas perpétuas, cidades no chão.',
      '',
      'Nenhuma memória deles perdurou',
      '7. Mas fica no trono pra sempre_o Senhor',
      'No trono erguido com_o fim de julgar',
      '8. o mundo e_os povos com justo padrão.',
      '',
      '9. Refúgio_é_o Senhor ao opresso também',
      'Refúgio nas horas de tribulação',
      '10. Confiam em Ti, quem Teu nome detém',
      'Porque Tu Senhor nunca deixas os Teus.',
      '',
      '11.Cantai os louvores ao Deus de Sião',
      'Dizei entre_os povos, os feitos de Deus',
      '12.  Pois lembra-se Aquele que_o sangue requer',
      'e não se esquece do_aflito_o clamor.',
      '',
      '13.  Tem misericórdia, de mim, ó Senhor',
      'E vê quantas dores me deram os maus',
      'Os que me odeiam me fazem sofrer',
      'Das portas da morte me salvas ó Deus',
      '',
      '14. E assim entrarei com louvor em Sião',
      'Cantando nas portas, Tua salvação',
      '15. Na cova que_abriram, nações cairão',
      'O laço que_armaram, prendeu-lhes o pé.',
      '',
      '16.  E bem conhecido se torna_o Senhor',
      'Por causa dos seus julgamentos que faz',
      'Enlaçado_o_ímpio, envolto está',
      'Nas obras traçadas pela própria mão.',
      '',
      '17. Os ímpios no_inferno lançados serão',
      'Também as nações que se_esquecem de Deus',
      '18. O pobre pra sempre_esquecido não é',
      'Nem se frustrará sempre_o seu esperar.',
      '',
      '19.  Levanta-Te_ó Deus, que não vença_o mortal',
      'E julgues na Tua presença_as nações',
      '20. Infunde-lhes medo Senhor; e_as nações',
      'Cientes serão que são simples mortais',
    ],
  ),
  Psalm(
    id: 10,
    title: 'Salmo 10b',
    lyrics: [
      'Por que, Senhor, ficas longe,',
      'Te escondes na provação?',
      'Os ímpios com grande arrogância',
      'Ao pobre vêm perseguir',
      'Nas próprias tramas que urdiram,',
      'Presas, pois, venham ser,',
      'Pois se vangloria o perverso',
      'Da sua cobiça vil',
      'Blasfema o avarento contra o Senhor e o maldiz',
      'Não investiga o perverso, pois',
      'Que Deus não existe é seu cogitar,',
      'Tem sempre os caminhos a prosperar',
      'Estão muito longe os juízos teus,',
      'E zomba dos oponentes seus',
      'Pois, pra si diz assim:',
      'Abalos nunca jamais terei nas gerações',
      '',
      'Tem ele cheia a sua boca',
      'De enganos e maldição,',
      'Insulto debaixo da língua,',
      'Pecado e transgressão',
      'Monta tocaia nas vilas',
      'A fim de espreitar,',
      'Trucida inocentes no ermo',
      'Qual fera a emboscar',
      'Na rede, o pobre já enlaçou e o prendeu',
      'Baixa e se arrasta e, em seu poder,',
      'Caíram aflitos. Diz ele a pensar:',
      'Não lembra o Senhor nem jamais verá',
      'O rosto virou e logo esqueceu',
      'Levanta, ó Deus, ergue a tua mão',
      'Ó Senhor, ó Senhor,',
      'Dos pobres não venhas te esquecer, ó meu Senhor',
      '',
      'Por que razão fica o ímpio',
      'Desprezando ao Senhor',
      'Pensando que Deus não se importa?',
      'Mas, tens visto, ó Senhor',
      'Ao sofrimento atentas',
      'Para os tomar nas mãos',
      'A ti se entrega o pobre',
      'Do órfão és defensor',
      'Quebranta o braço do homem mau, transgressor',
      'Sonda-lhes toda maldade até',
      'Não mais encontrar. Rei eterno é o Senhor',
      'Da terra de Deus somem-se as nações',
      'Dos mansos tu tens escutado a voz',
      'E firmarás os seus corações. Seu clamor ouvirás',
      'E, assim, ninguém lhes trará terror, pois justo és',

    ],
  ),
  Psalm(
    id: 11,
    title: 'Salmo 11b',
    lyrics: [
      'Meu refúgio está em Deus',
      'Como podes me dizer',
      '“Qual ave foge ao monte seu',
      'Assim fujas também',
      'Pois eis que os ímpios vão',
      'Têm já pronto o arco à mão',
      'Para às ocultas disparar',
      'Nos justos de coração',
      '',
      'Quando há destruição',
      'Fundamentos já não são',
      'Que pode o justo fazer, então,',
      'Se nesta vil condição?”',
      'No templo, está o Senhor',
      'Tem nos céus o trono seu',
      'Seus olhos sondam com atenção',
      'Os filhos dos homens vê',
      '',
      'E ao justo aprova Deus,',
      'Mas odeia o homem mau,',
      'E aquele que violência faz',
      'Deus o abomina já',
      'Javé fará chover',
      'Fogo, enxofre, sobre os maus',
      'E vento abrasador será',
      'A taça que lhes dará',
      '',
      'Pois justo é o Senhor',
      'Ele ama a retidão,',
      'E cada um que justo for',
      'A face lhe verá',
      'Pois justo é o Senhor',
      'Ele ama a retidão',
      'E cada um que justo for',
      'A face lhe verá ',
    ],
  ),
  Psalm(
    id: 12,
    title: 'Salmo 12',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 13,
    title: 'Salmo 13b',
    lyrics: [
      'Senhor, até quando tu te esquecerás',
      'De mim, para sempre, o rosto ocultarás?',
      'Até quando na alma eu relutarei',
      'Triste cada dia em meu coração?',
      '',
      'Até quando contra mim se erguerá',
      'O meu inimigo? Ouve-me, ó Senhor',
      'Me ilumina os olhos e responde-me',
      'Que eu da morte o sono não venha dormir',
      '',
      'Para que não diga o inimigo meu:',
      '“Indo contra ele, eu prevaleci”',
      'Não se regozijem adversários meus,',
      'Não se alegrem eles vindo eu vacilar',
      '',
      'Quanto a mim, na tua graça confiarei',
      'E exultarei na tua salvação',
      'Com grande alegria no meu coração,',
      'Canto a Deus, pois tem me feito muito bem ',
    ],
  ),
  Psalm(
    id: 14,
    title: 'Salmo 14',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 15,
    title: 'Salmo 15b',
    lyrics: [
      '\u00B9Quem vai morar, Senhor,',
      'no teu santo templo?',
      'Quem há de residir',
      'no teu monte, ó Deus?',
      '\u00B2Quem vive em retidão,',
      'tem justo proceder',
      'Só a verdade diz',
      'no seu coração.',
      '',
      '\u00B3Não vive a difamar,',
      'não faz mal a outrem:',
      'Ao seu vizinho não',
      'quer injuriar',
      '\u2074Despreza o homem vil,',
      'honra ao que teme a Deus;',
      'Jura com perda,',
      'até, mas não volta atrás.',
      '',
      '\u2075O seu dinheiro não',
      'cede com usura,',
      'Suborno algum jamais',
      'pensa receber',
      'Para incriminar',
      'quem inocente é',
      'Quem assim proceder,',
      'não se abalará.',
    ],
  ),
  Psalm(
    id: 16,
    title: 'Salmo 16b',
    lyrics: [
      'Guarda-me, ó Deus, pois em ti eu me abrigo',
      'Minha alma diz que tu és meu Senhor',
      'Além de ti outro bem eu não tenho',
      'E nos teus santos está meu prazer',
      'Há muitas punições, penalidades mil',
      'Pra quem por deuses trocar o Senhor',
      'Jamais darei sacrifício a tais deuses,',
      'A quem meus lábios não pronunciarão',
      '',
      'És minha taça, Senhor, minha herança',
      'Da minha sorte o arrimo tu és',
      'Tenho as divisas em áreas amenas',
      'Minha herança é formosa e sem par',
      'Bendigo o meu Senhor, que a mim conselhos traz',
      'E, à noite, o coração vem me ensinar',
      'Tenho o Senhor sempre à minha presença',
      'Ele à direita, abalado não sou',
      '',
      'Meu coração bem alegre exulta',
      'Meu corpo a salvo repouso terá',
      'Minha alma não deixarás no abismo',
      'Nem o teu Santo provar corrupção',
      'Tu me farás saber por onde devo andar',
      'Sim, o caminho da vida enxergar',
      'Há pleno gozo na tua presença',
      'Na tua destra, delícias sem fim ',

    ],
  ),
  Psalm(
    id: 17,
    title: 'Salmo 17',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 18,
    title: 'Salmo 18',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 19,
    title: 'Salmo 19b',
    lyrics: [
      'Os céus proclamam, sim, a glória do Senhor,',
      'E_o firmamento_expõe as obras das suas mãos,',
      'E discursa_o dia_ao que vem depois,',
      'E_a noite_à outra faz saber.',
      '',
      'Linguagem nem palavra_ou som se ouve_algum,',
      'Porém se faz ouvir na terra_a sua voz,',
      'E_as palavras soam até_os confins.',
      'Aí, pôs uma tenda_ao sol,',
      '',
      'Que,_assim como herói, os céus a percorrer,',
      'Dos aposentos sai qual noivo_a se_alegrar',
      'E de um extremo ao outro vai',
      'E nada_escapa_ao seu calor.',
      '',
      'Perfeita_é_a lei de Deus, restaura_o coração.',
      'Seu testemunho fiel ao simples dá o saber.',
      'Do Senhor mui reto_os preceitos são',
      'E_alegram bem o coração.',
      '',
      'O mandamento seu é puro_e dá visão,',
      'É claro o seu temor, pra sempre durará.',
      'Verdadeiros são os juízos seus',
      'E justos todos por igual.',
      '',
      'Mais desejáveis são que_o_ouro puro_e bom,',
      'Mais doces do que_o mel que_o favo destilou',
      'E_ao teu servo trazem exortação.',
      'Há grande prêmio_em os guardar.',
      '',
      'Quem pode discernir as próprias transgressões?',
      'Das que_eu não posso ver perdoa-me, Senhor.',
      'Da soberba guarda teu servo,_ó Deus.',
      'Jamais me venha dominar.',
      '',
      'E justo, pois, serei, de grande transgressão.',
      'Aquilo que_eu falar e_o coração meditar',
      'Agradáveis sejam a ti, Senhor,',
      'Rochedo meu e Redentor. ',
    ],
  ),
  Psalm(
    id: 20,
    title: 'Salmo 20b',
    lyrics: [
      '1. Que_a ti resposta dê_o Senhor no dia da_aflição',
      'Te_eleve_em segurança_o nome do Deus de Jacó',
      '2. Do santuário,_envie socorro_e te sustenha de Sião',
      '3. De tuas ofertas e_holocaustos lembre_e_aceite Deus',
      '',
      '4. Segundo quer teu coração, conceda-te_o Senhor',
      'E_os teus desígnios todos eles realize Deus',
      '5. Celebraremos tua vitória, jubilosos, todos nós',
      'E_hastearemos nós pendões em nome do Senhor',
      '',
      'E_a todos os teus votos satisfaça_o nosso Deus',
      '6. E_agora sei que_o seu ungido_o Senhor salvará',
      'E_a Ele, do seu santo céu, o Senhor lhe responderá',
      'Com_a destra vitoriosa_e forte, lhe responderá',
      '',
      '7. Os homens em cavalos, carros, confiança têm,',
      'Mas nós nos gloriaremos, sim, no nome do Senhor',
      '8. Os tais se encurvam, tombam, mas de pé nos manteremos, pois',
      'Oh, dá, Senhor, vitória ao rei, clamamos, ouve,_ó Deus ',
    ],
  ),
  Psalm(
    id: 21,
    title: 'Salmo 21b',
    lyrics: [
      'Na tua força, ó Deus, o rei se alegra',
      'E como exulta com tua salvação',
      'Satisfizeste-lhe o desejo da alma,',
      'Não lhe negaste as orações que fez',
      'Das bênçãos de bondade tu o supres',
      'Coroa de ouro puro lhe darás',
      '',
      'A vida a ti ele pediu e deste',
      'Longevidade para sempre, sim',
      'De majestade e esplendor vestiu-lhe',
      'Grande é a glória da tua salvação',
      'Por bênção para sempre o colocaste',
      'Com tua presença o encheste de prazer',
      '',
      'Do Deus altíssimo, por sua graça',
      'O rei, então, jamais vacilará',
      'Pois ele no Senhor tem confiança',
      'A tua mão, então, alcançará',
      'Teus inimigos, todos que te odeiam',
      'A tua destra os apanhará',
      '',
      'Os tornarás como em fornalha ardente',
      'Ao te manifestares, ó Senhor',
      'Na sua indignação, a todos eles',
      'Consumirá e o fogo os tragará',
      'Destruirás da terra a sua prole',
      'E os filhos deles que entre os homens há',
      '',
      'Se intentarem contra ti maldade,',
      'Tramando intrigas, não consumarão',
      'Porquanto lhes farás voltar as costas',
      'Teu arco o rosto deles mirarás',
      'Senhor, te exalta, pois na tua força',
      'E ao teu poder cantaremos louvor ',
    ],
  ),
  Psalm(
    id: 22,
    title: 'Salmo 22b',
    lyrics: [
      'Deus meu, Deus meu, por que tu desamparaste a mim?',
      'Por que se acham longe de minha salvação',
      'Meu grito, meu bramido, que dia e noite a ti',
      'Dirijo e não respondes, sossego não me vem',
      '',
      'Contudo, tu és santo, entronizado estás',
      'No meio dos louvores, louvores de Israel',
      'Em ti os pais confiaram, livraste-os, ó Senhor',
      'Clamaram e escaparam, não viram confusão',
      '',
      'Sou verme, não sou homem, opróbrio de homens sou',
      'Do povo desprezado, zombado dos que me veem',
      'Meneiam a cabeça e os lábios a mover',
      'Em Deus confiou que o livre, pois nele tem prazer',
      '',
      'Porém tu és aquele que a mim fizeste nascer',
      'Me preservaste ainda no seio de minha mãe',
      'Desde o meu nascimento, a ti me entreguei',
      'Desde o ventre materno, Senhor, tu és meu Deus',
      '',
      'De mim não te afastes, pois aflição já vem',
      'Não há quem me acuda, pois touros de Basã,',
      'Mui fortes, me rodeiam qual boca de leão',
      'Que, contra mim rugindo, quer me despedaçar',
      '',
      'Como água, derramei-me, e os ossos todos meus',
      'Estão desconjuntados, também meu coração',
      'Qual cera se tornou e em mim se derreteu,',
      'Secou-se a minha força e um caco se tornou',
      '',
      'Pegada a minha língua ao céu da boca está',
      'E, assim, ao pó da morte fizeste-me deitar',
      'Cercado estou de cães, uma súcia de homens maus',
      'Cercando, me traspassam meus pés e minhas mãos',
      '',
      'E todos os meus ossos eu posso a eles contar,',
      'Me encaram todos eles, olhando para mim',
      'Repartem minhas vestes, e a túnica, porém,',
      'Sobre ela todos eles a sorte vão lançar',
      '',
      'Porém, Senhor, de mim, tu não venhas te afastar',
      'Te apressa em socorrer-me, pois força minha és',
      'Salvar-me vem da espada, das presas, sim, do cão',
      'Dos búfalos, seus chifres, das fauces do leão',
      '',
      'A meus irmãos, teu nome, então, declararei',
      'Cantar-te-ei louvores em meio à congregação',
      'Vós que temeis a Deus, louvor e glória dai',
      'Sim, reverenciai-o, vós filhos de Israel',
      '',
      'Não desprezou do aflito e nem abominou',
      'A sua dor, nem dele seu rosto ocultou,',
      'Mas escutou quando ele socorro lhe gritou',
      'De ti vem meu louvor, sim, na grande reunião',
      '',
      'Diante dos que o temem, meus votos cumprirei',
      'Os sofredores hão de comer e se fartar',
      'Senhor, os que te buscam teu nome louvarão',
      'E viva para sempre o vosso coração',
      '',
      'Da terra os seus limites do Senhor lembrarão',
      'E até os confins da terra, pois se converterão',
      'E, juntas, as famílias de todas as nações',
      'Virão perante Ele e, então, se prostrarão',
      '',
      'Pois do Senhor é o reino, governa sobre as nações',
      'Da terra os opulentos hão de comer e adorar',
      'E os que ao pó desceram a Deus vão se prostrar',
      'E até quem sua vida não pode preservar',
      '',
      'E à geração vindoura falar-se-á do Senhor',
      'E a descendência a Ele também o servirá',
      'Hão de sua justiça a todos proclamar',
      'E às gerações futuras dirão que Deus o fez ',
    ],
  ),
  Psalm(
    id: 23,
    title: 'Salmo 23b',
    lyrics: [
      '\u00B9O meu pastor é o Senhor',
      'E nada me faltará',
      'Em pastos verdes faz-me deitar,',
      'As fontes de paz conduz.',
      '',
      "\u00B2Minha'alma Deus bem restaurar",
      'E guia meu caminhar:',
      'Por justas veredas faz-me andar',
      'Por causa do nome Seu.',
      '',
      '\u00B3Se a morte me ameaçar',
      'No vale da escuridão',
      'Não temerei mal nenhum',
      'Pois tu comigo estás.',
      '',
      '\u2074A tua vara e o teu bordão',
      'A mim consolo dão',
      'E mesa pões diante de mim.',
      'Perante inimigos meus.',
      '',
      '\u2075Com óleo a fronte unges-me',
      'Transborda o copo meu',
      'Bondade tua e compaixão',
      'Deveras me sequirão.',
      '',
      '\u2076Sim, todos os dias me seguirão,',
      'Por todo o meu viver',
      'E eternamente habitarei',
      'Na casa do Senhor.',
    ],
  ),
  Psalm(
    id: 24,
    title: 'Salmo 24',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 25,
    title: 'Salmo 25',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 26,
    title: 'Salmo 26',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 27,
    title: 'Salmo 27',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 28,
    title: 'Salmo 28',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 29,
    title: 'Salmo 29',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 30,
    title: 'Salmo 30',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 31,
    title: 'Salmo 31',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 32,
    title: 'Salmo 32',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 33,
    title: 'Salmo 33',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 34,
    title: 'Salmo 34',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 35,
    title: 'Salmo 35',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 36,
    title: 'Salmo 36',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 37,
    title: 'Salmo 37',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 38,
    title: 'Salmo 38',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 39,
    title: 'Salmo 39',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 40,
    title: 'Salmo 40',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 41,
    title: 'Salmo 41',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 42,
    title: 'Salmo 42',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 43,
    title: 'Salmo 43',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 44,
    title: 'Salmo 44',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 45,
    title: 'Salmo 45',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 46,
    title: 'Salmo 46',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 47,
    title: 'Salmo 47',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 48,
    title: 'Salmo 48',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 49,
    title: 'Salmo 49',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 50,
    title: 'Salmo 50',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 51,
    title: 'Salmo 51',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 52,
    title: 'Salmo 52',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 53,
    title: 'Salmo 53',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 54,
    title: 'Salmo 54',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 55,
    title: 'Salmo 55',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 56,
    title: 'Salmo 56',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 57,
    title: 'Salmo 57',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 58,
    title: 'Salmo 58',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 59,
    title: 'Salmo 59',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 60,
    title: 'Salmo 60',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 61,
    title: 'Salmo 61',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 62,
    title: 'Salmo 62',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 63,
    title: 'Salmo 63',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 64,
    title: 'Salmo 64',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 65,
    title: 'Salmo 65',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 66,
    title: 'Salmo 66',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 67,
    title: 'Salmo 67',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 68,
    title: 'Salmo 68',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 69,
    title: 'Salmo 69',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 70,
    title: 'Salmo 70',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 71,
    title: 'Salmo 71',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 72,
    title: 'Salmo 72',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 73,
    title: 'Salmo 73',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 74,
    title: 'Salmo 74',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 75,
    title: 'Salmo 75',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 76,
    title: 'Salmo 76',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 77,
    title: 'Salmo 77',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 78,
    title: 'Salmo 78',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 79,
    title: 'Salmo 79',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 80,
    title: 'Salmo 80',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 81,
    title: 'Salmo 81',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 82,
    title: 'Salmo 82',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 83,
    title: 'Salmo 83',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 84,
    title: 'Salmo 84',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 85,
    title: 'Salmo 85',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 86,
    title: 'Salmo 86',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 87,
    title: 'Salmo 87',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 88,
    title: 'Salmo 88',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 89,
    title: 'Salmo 89',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 90,
    title: 'Salmo 90',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 91,
    title: 'Salmo 91',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 92,
    title: 'Salmo 92',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 93,
    title: 'Salmo 93',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 94,
    title: 'Salmo 94',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 95,
    title: 'Salmo 95',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 96,
    title: 'Salmo 96',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 97,
    title: 'Salmo 97',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 98,
    title: 'Salmo 98',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 99,
    title: 'Salmo 99',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 100,
    title: 'Salmo 100',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 101,
    title: 'Salmo 101',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 102,
    title: 'Salmo 102',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 103,
    title: 'Salmo 103',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 104,
    title: 'Salmo 104',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 105,
    title: 'Salmo 105',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 106,
    title: 'Salmo 106',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 107,
    title: 'Salmo 107',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 108,
    title: 'Salmo 108',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 109,
    title: 'Salmo 109',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 110,
    title: 'Salmo 110',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 111,
    title: 'Salmo 111',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 112,
    title: 'Salmo 112',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 113,
    title: 'Salmo 113',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 114,
    title: 'Salmo 114',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 115,
    title: 'Salmo 115',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 116,
    title: 'Salmo 116',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 117,
    title: 'Salmo 117',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 118,
    title: 'Salmo 118',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 119,
    title: 'Salmo 119',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 120,
    title: 'Salmo 120',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 121,
    title: 'Salmo 121',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 122,
    title: 'Salmo 122',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 123,
    title: 'Salmo 123',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 124,
    title: 'Salmo 124',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 125,
    title: 'Salmo 125',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 126,
    title: 'Salmo 126',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 127,
    title: 'Salmo 127',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 128,
    title: 'Salmo 128',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 129,
    title: 'Salmo 129',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 130,
    title: 'Salmo 130',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 131,
    title: 'Salmo 131',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 132,
    title: 'Salmo 132',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 133,
    title: 'Salmo 133',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 134,
    title: 'Salmo 134',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 135,
    title: 'Salmo 135',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 136,
    title: 'Salmo 136',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 137,
    title: 'Salmo 137',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 138,
    title: 'Salmo 138',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 139,
    title: 'Salmo 139',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 140,
    title: 'Salmo 140',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 141,
    title: 'Salmo 141',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 142,
    title: 'Salmo 142',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 143,
    title: 'Salmo 143',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 144,
    title: 'Salmo 144',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 145,
    title: 'Salmo 145',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 146,
    title: 'Salmo 146',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 147,
    title: 'Salmo 147',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 148,
    title: 'Salmo 148',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 149,
    title: 'Salmo 149',
    lyrics: [
      '',
    ],
  ),
  Psalm(
    id: 150,
    title: 'Salmo 150',
    lyrics: [
      '',
    ],
  ),
];
